name: Build release command line

on:
  workflow_dispatch:
  push:
    branches:
      - main

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build-task:
    runs-on: ${{ fromJSON('["ubuntu-latest", "self-hosted"]')[github.repository == 'github/docs-internal'] }}
    defaults:
      run:
        working-directory: src/GrantDatabase.CommandLine/
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build
      - name: Publish
        run: dotnet publish -c Release -r ubuntu.22.04-x64 -p:PublishSingleFile=true --self-contained true
      - name: Create tar gzip package
        working-directory: src/GrantDatabase.CommandLine/bin/Release/net7.0/ubuntu.22.04-x64/publish/
        run: |
          tar --create --gzip --file dbcmd.tar.gz dbcmd
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0
          files: |
            src/GrantDatabase.CommandLine/bin/Release/net7.0/ubuntu.22.04-x64/publish/dbcmd.tar.gz
